/***********************************************************************************************************************************
Standalone test for src/mysql/interface.c — mysqlAutoCnfReadUuid

Writes a synthetic auto.cnf and verifies the UUID extraction. Also covers:
  - Missing file → returns NULL (valid pre-bootstrap state)
  - Wrong-length UUID value → throws FormatError
  - Multiple sections → only server-uuid line is captured
***********************************************************************************************************************************/
#include <build.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#include "common/debug.h"
#include "common/error/error.h"
#include "common/log.h"
#include "common/stackTrace.h"
#include "mysql/interface.h"
#include "storage/posix/storage.h"

static int testFailures = 0;

static void
expect(const char *const what, const bool condition)
{
    printf("  %s  %s\n", condition ? "PASS" : "FAIL", what);
    if (!condition)
        testFailures++;
}

static void
writeFile(const char *const path, const char *const contents)
{
    FILE *const fp = fopen(path, "w");
    if (fp == NULL) THROW(FileWriteError, "fopen failed");
    fputs(contents, fp);
    fclose(fp);
}

/**********************************************************************************************************************************/
int
main(void)
{
    static const ErrorHandlerFunction errorHandlerList[] = {stackTraceClean, memContextClean};
    errorHandlerSet(errorHandlerList, LENGTH_OF(errorHandlerList));

    logInit(logLevelWarn, logLevelError, logLevelOff, false, 0, 1, false);

    int rc = 0;

    TRY_BEGIN()
    {
        printf("auto.cnf reader tests:\n");

        // Setup: a temp dir for synthetic datadirs
        const char *const tmpRoot = "/tmp/mybackrest-autocnf-test";
        mkdir(tmpRoot, 0755);

        const Storage *const storage = storagePosixNewP(STR(tmpRoot));

        // ---- Test 1: well-formed auto.cnf ----
        writeFile(
            "/tmp/mybackrest-autocnf-test/auto.cnf",
            "[auto]\nserver-uuid=8c0fd6f0-bf8f-11ee-9821-0242ac120002\n");

        String *const uuid1 = mysqlAutoCnfReadUuid(storage, STRDEF("."));
        expect("well-formed uuid extracted", uuid1 != NULL && strEqZ(uuid1, "8c0fd6f0-bf8f-11ee-9821-0242ac120002"));

        // ---- Test 2: extra whitespace + trailing comment-style content ----
        writeFile(
            "/tmp/mybackrest-autocnf-test/auto.cnf",
            "# generated by mysqld\n[auto]\n   server-uuid =   ffeeddcc-bbaa-9988-7766-554433221100   \n[other]\nfoo=bar\n");

        String *const uuid2 = mysqlAutoCnfReadUuid(storage, STRDEF("."));
        expect("uuid extracted with surrounding whitespace", uuid2 != NULL && strEqZ(uuid2, "ffeeddcc-bbaa-9988-7766-554433221100"));

        // ---- Test 3: missing file → NULL ----
        unlink("/tmp/mybackrest-autocnf-test/auto.cnf");
        String *const uuid3 = mysqlAutoCnfReadUuid(storage, STRDEF("."));
        expect("missing auto.cnf returns NULL", uuid3 == NULL);

        // ---- Test 4: malformed UUID (wrong length) → FormatError ----
        writeFile("/tmp/mybackrest-autocnf-test/auto.cnf", "[auto]\nserver-uuid=too-short\n");

        bool threw = false;
        TRY_BEGIN()
        {
            mysqlAutoCnfReadUuid(storage, STRDEF("."));
        }
        CATCH(FormatError)
        {
            threw = true;
        }
        TRY_END();

        expect("wrong-length UUID throws FormatError", threw);

        // Cleanup
        unlink("/tmp/mybackrest-autocnf-test/auto.cnf");
        rmdir(tmpRoot);
    }
    CATCH_FATAL()
    {
        printf("FATAL: %s\n%s\n", errorMessage(), errorStackTrace());
        rc = 1;
    }
    TRY_END();

    if (testFailures > 0)
    {
        printf("\n%d assertion(s) failed\n", testFailures);
        rc = 1;
    }
    else if (rc == 0)
    {
        printf("\nAll assertions passed\n");
    }

    return rc;
}
