/***********************************************************************************************************************************
Restore Prepare Phase

Both prepareWriteRecoveryFiles and prepareInvokeMysqld are now real. Together they implement the user-chosen mysqld-driven crash
recovery hand-off — myBackRest writes a single-shot recovery cnf + sql, then forks mysqld which replays InnoDB redo and exits via
SHUTDOWN. No GPLv2 InnoDB recovery code is linked into the MIT mybackrest binary.
***********************************************************************************************************************************/
#include <build.h>

#include <stdlib.h>
#include <sys/wait.h>
#include <unistd.h>

#include "command/restore/prepare.h"
#include "common/debug.h"
#include "common/fork.h"
#include "common/log.h"
#include "common/type/buffer.h"
#include "common/type/string.h"
#include "common/type/stringList.h"
#include "mysql/binary.h"
#include "mysql/manifest.h"
#include "storage/posix/storage.h"

#define MYBACKREST_RECOVERY_CNF                                     "mybackrest_recovery.cnf"
#define MYBACKREST_RECOVERY_SQL                                     "mybackrest_recovery.sql"
#define MYBACKREST_RECOVERY_PID                                     "mybackrest_recovery.pid"
#define MYBACKREST_RECOVERY_LOG                                     "mybackrest_recovery.log"
#define MYBACKREST_RECOVERY_XA_CNF                                  "mybackrest_recovery_xa.cnf"
#define MYBACKREST_RECOVERY_XA_LOG                                  "mybackrest_recovery_xa.log"

/**********************************************************************************************************************************/
FN_EXTERN void
prepareWriteRecoveryFiles(
    const Storage *const restoreStorage, const String *const restorePath, const String *const mysqldPath,
    const MysqlVendor vendor)
{
    FUNCTION_LOG_BEGIN(logLevelDebug);
        FUNCTION_LOG_PARAM(STORAGE, restoreStorage);
        FUNCTION_LOG_PARAM(STRING, restorePath);
        FUNCTION_LOG_PARAM(STRING, mysqldPath);
        FUNCTION_LOG_PARAM(STRING_ID, vendor);
    FUNCTION_LOG_END();

    ASSERT(restoreStorage != NULL);
    ASSERT(restorePath != NULL);

    MEM_CONTEXT_TEMP_BEGIN()
    {
        // Compose the recovery cnf. Each option uses --long-form syntax so it works under either MySQL or MariaDB without
        // needing per-vendor branching.
        String *const cnf = strNewFmt(
            "# Generated by myBackRest — single-shot recovery configuration.\n"
            "# Run mysqld --defaults-file=%s/%s; the embedded init-file will issue SHUTDOWN; once InnoDB redo recovery\n"
            "# completes, leaving the datadir clean for normal startup with your own config afterwards.\n"
            "[mysqld]\n"
            "datadir = %s\n"
            "skip-networking = ON\n"
            "skip-grant-tables = OFF\n"
            "innodb-read-only = OFF\n"
            "innodb-fast-shutdown = 0\n"
            "init-file = %s/%s\n"
            "pid-file = %s/%s\n"
            "log-error = %s/%s\n",
            strZ(restorePath), MYBACKREST_RECOVERY_CNF,
            strZ(restorePath),
            strZ(restorePath), MYBACKREST_RECOVERY_SQL,
            strZ(restorePath), MYBACKREST_RECOVERY_PID,
            strZ(restorePath), MYBACKREST_RECOVERY_LOG);

        const String *const cnfPath = strNewFmt("%s/%s", strZ(restorePath), MYBACKREST_RECOVERY_CNF);
        storagePutP(storageNewWriteP(restoreStorage, cnfPath), BUFSTR(cnf));

        // Compose the SQL: a single SHUTDOWN; — innodb-fast-shutdown=0 ensures all dirty pages flush before the server exits, so
        // when the user's own mysqld starts later it sees a fully-clean datadir instead of replaying the recovery again.
        const String *const sql = STRDEF("-- Generated by myBackRest. Fires once via --init-file at end of recovery.\nSHUTDOWN;\n");
        const String *const sqlPath = strNewFmt("%s/%s", strZ(restorePath), MYBACKREST_RECOVERY_SQL);
        storagePutP(storageNewWriteP(restoreStorage, sqlPath), BUFSTR(sql));

        // MariaDB extra: write a second, one-shot cnf with tc-heuristic-recover=COMMIT. The orchestrator's hot backup can
        // capture an InnoDB tablespace state mid-2PC (transaction PREPARED but its commit event not in the binlog that
        // landed in the backup). When mariadbd boots and finds such a prepared XA without the binlog to coordinate from,
        // it refuses to start. tc-heuristic-recover instructs mariadbd to COMMIT the prepared transaction(s) and exit; a
        // subsequent normal start sees a clean datadir. (Full fix is to back up the binlogs covering the LSN range via
        // mybackrest archive-push — Phase F. This XA cnf is the restore-side bridge until that lands.)
        if (vendor == mysqlVendorMariadb)
        {
            String *const xaCnf = strNewFmt(
                "# Generated by myBackRest — one-shot MariaDB XA-prepared resolution pass.\n"
                "# Used BEFORE the main recovery cnf to commit any prepared transactions captured in the backup. mariadbd\n"
                "# exits after committing (\"Please restart without --tc-heuristic-recover\"). prepareInvokeMysqld chains\n"
                "# this run with the main recovery run automatically when vendor==MariaDB.\n"
                "[mysqld]\n"
                "datadir = %s\n"
                "skip-networking = ON\n"
                "tc-heuristic-recover = COMMIT\n"
                "pid-file = %s/%s\n"
                "log-error = %s/%s\n",
                strZ(restorePath),
                strZ(restorePath), MYBACKREST_RECOVERY_PID,
                strZ(restorePath), MYBACKREST_RECOVERY_XA_LOG);

            const String *const xaCnfPath = strNewFmt("%s/%s", strZ(restorePath), MYBACKREST_RECOVERY_XA_CNF);
            storagePutP(storageNewWriteP(restoreStorage, xaCnfPath), BUFSTR(xaCnf));

            LOG_INFO_FMT(
                "MariaDB XA pre-pass cnf written: %s (will resolve prepared transactions before main recovery)",
                strZ(xaCnfPath));
        }

        if (mysqldPath != NULL)
            LOG_INFO_FMT("recovery files written; run: %s --defaults-file=%s/%s", strZ(mysqldPath), strZ(restorePath), MYBACKREST_RECOVERY_CNF);
        else
            LOG_INFO_FMT("recovery files written: %s and %s", strZ(cnfPath), strZ(sqlPath));
    }
    MEM_CONTEXT_TEMP_END();

    FUNCTION_LOG_RETURN_VOID();
}

/***********************************************************************************************************************************
Scan a recovery log file for the MariaDB "Found N prepared transactions!" signature. Used to decide whether to fall back to the
tc-heuristic-recover XA pre-pass after a failed first recovery attempt. Returns true if the marker is found.
***********************************************************************************************************************************/
static bool
logHasPreparedTransactionError(const Storage *const storage, const String *const path)
{
    bool found = false;

    TRY_BEGIN()
    {
        Buffer *const buf = storageGetP(storageNewReadP(storage, path, .ignoreMissing = true));
        if (buf != NULL && bufUsed(buf) > 0)
        {
            // strstr against the canonical phrase. Both MariaDB 10.x and 11.x emit "Found N prepared transactions!".
            const char *const zBuf = (const char *)bufPtrConst(buf);
            found = memmem(zBuf, bufUsed(buf), "prepared transaction", strlen("prepared transaction")) != NULL;
        }
    }
    CATCH_ANY()
    {
        // Log unreadable — treat as "no marker found" and let the caller propagate the original error
    }
    TRY_END();

    return found;
}

/***********************************************************************************************************************************
Fork mysqld with a given defaults-file cnf and wait for it to exit. Returns the exit code (0 on clean exit; non-zero on
mysqld error). Used three ways:
  - Main recovery (allowNonZeroExit=false): a non-zero is treated as caller-actionable
  - MariaDB XA pre-pass (allowNonZeroExit=true): mariadbd ALWAYS errors with "Can't init tc log" after a tc-heuristic-recover
    pass, so non-zero is expected and silently accepted
***********************************************************************************************************************************/
static int
runMysqldOneShot(
    const String *const mysqldPath, const String *const restorePath, const String *const cnfFile,
    const String *const logFile, const bool allowNonZeroExit, const char *const label)
{
    StringList *const argv = strLstNew();
    strLstAdd(argv, mysqldPath);
    strLstAdd(argv, strNewFmt("--defaults-file=%s/%s", strZ(restorePath), strZ(cnfFile)));

    LOG_INFO_FMT("%s: %s --defaults-file=%s/%s", label, strZ(mysqldPath), strZ(restorePath), strZ(cnfFile));

    const pid_t pid = forkSafe();

    if (pid == 0)
    {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wcast-qual"
        THROW_ON_SYS_ERROR_FMT(
            execvp(strZ(strLstGet(argv, 0)), UNCONSTIFY(char **, strLstPtr(argv))) == -1, ExecuteError,
            "unable to exec mysqld at '%s'", strZ(mysqldPath));
#pragma GCC diagnostic pop

        exit(127);
    }

    int status;
    const pid_t waited = waitpid(pid, &status, 0);
    THROW_ON_SYS_ERROR_FMT(waited == -1, ExecuteError, "waitpid failed for mysqld %s", label);

    if (!WIFEXITED(status))
    {
        THROW_FMT(
            ExecuteError, "mysqld %s did not exit normally — check %s/%s for details",
            label, strZ(restorePath), strZ(logFile));
    }

    const int exitCode = WEXITSTATUS(status);

    if (exitCode != 0 && !allowNonZeroExit)
    {
        // Caller decides whether to retry (e.g. with XA pre-pass) — just return the code, don't throw here. (Throwing
        // would prevent the caller from inspecting the log to choose a fallback.)
        LOG_DETAIL_FMT("mysqld %s exited with status %d — see %s/%s", label, exitCode, strZ(restorePath), strZ(logFile));
    }
    else if (allowNonZeroExit && exitCode != 0)
    {
        LOG_DETAIL_FMT("mysqld %s exited with status %d (expected for tc-heuristic-recover pass)", label, exitCode);
    }

    return exitCode;
}

/**********************************************************************************************************************************/
FN_EXTERN void
prepareInvokeMysqld(const String *const mysqldPath, const String *const restorePath, const MysqlVendor vendor)
{
    FUNCTION_LOG_BEGIN(logLevelDebug);
        FUNCTION_LOG_PARAM(STRING, mysqldPath);
        FUNCTION_LOG_PARAM(STRING, restorePath);
        FUNCTION_LOG_PARAM(STRING_ID, vendor);
    FUNCTION_LOG_END();

    ASSERT(mysqldPath != NULL);
    ASSERT(restorePath != NULL);

    MEM_CONTEXT_TEMP_BEGIN()
    {
        MysqlBinaryInfo *const binInfo = mysqlBinaryProbe(mysqldPath);
        LOG_INFO_FMT(
            "recovery binary: %s — vendor=%u version=%u (%s)",
            strZ(mysqldPath), (unsigned int)binInfo->vendor, binInfo->versionNum,
            binInfo->versionRaw != NULL ? strZ(binInfo->versionRaw) : "(unparsed)");

        // Strategy: try the main recovery cnf first. If it succeeds, done. If it fails, look at the recovery log: on
        // MariaDB a failure mentioning prepared transactions means the backup captured an in-flight 2PC that needs the
        // XA pre-pass to resolve heuristically. Run that pass + retry the main recovery. This is robust to backups that
        // were missing the binlog covering the 2PC commit (mariabackup's --tc-heuristic-recover convention).
        //
        // For MySQL/Percona the same prepared-transaction error doesn't happen — InnoDB's redo replay handles the in-
        // flight 2PC via its tc-log machinery without needing an external heuristic flag. Any non-zero exit from main
        // recovery on those vendors is genuinely unrecoverable.
        const String *const restoreStorageRel = STRDEF(".");
        (void)restoreStorageRel;

        int rc = runMysqldOneShot(
            mysqldPath, restorePath, STR(MYBACKREST_RECOVERY_CNF), STR(MYBACKREST_RECOVERY_LOG),
            /*allowNonZeroExit*/ vendor == mysqlVendorMariadb, "recovery");

        if (rc != 0 && vendor == mysqlVendorMariadb)
        {
            const String *const logPath = strNewFmt("%s/%s", strZ(restorePath), MYBACKREST_RECOVERY_LOG);
            const Storage *const restoreStorage = storagePosixNewP(strNewFmt("%s", strZ(restorePath)));

            if (logHasPreparedTransactionError(restoreStorage, STRDEF(MYBACKREST_RECOVERY_LOG)))
            {
                LOG_INFO_FMT(
                    "MariaDB recovery saw prepared XA transactions — running XA pre-pass then retrying (%s)",
                    strZ(logPath));

                runMysqldOneShot(
                    mysqldPath, restorePath, STR(MYBACKREST_RECOVERY_XA_CNF), STR(MYBACKREST_RECOVERY_XA_LOG),
                    /*allowNonZeroExit*/ true, "XA pre-pass");

                rc = runMysqldOneShot(
                    mysqldPath, restorePath, STR(MYBACKREST_RECOVERY_CNF), STR(MYBACKREST_RECOVERY_LOG),
                    /*allowNonZeroExit*/ false, "recovery retry");
            }

            if (rc != 0)
            {
                THROW_FMT(
                    ExecuteError, "mysqld recovery exited with status %d after XA pre-pass — check %s/%s",
                    rc, strZ(restorePath), MYBACKREST_RECOVERY_LOG);
            }
        }
        else if (rc != 0)
        {
            THROW_FMT(
                ExecuteError, "mysqld recovery exited with status %d — check %s/%s",
                rc, strZ(restorePath), MYBACKREST_RECOVERY_LOG);
        }

        LOG_INFO("mysqld recovery completed; datadir is clean and ready for normal startup");
    }
    MEM_CONTEXT_TEMP_END();

    FUNCTION_LOG_RETURN_VOID();
}

/**********************************************************************************************************************************/
FN_EXTERN void
prepareVerifyCompatibility(
    const Storage *const backupStorage, const String *const backupPath, const String *const mysqldPath, const bool allowMajorSkew)
{
    FUNCTION_LOG_BEGIN(logLevelDebug);
        FUNCTION_LOG_PARAM(STORAGE, backupStorage);
        FUNCTION_LOG_PARAM(STRING, backupPath);
        FUNCTION_LOG_PARAM(STRING, mysqldPath);
        FUNCTION_LOG_PARAM(BOOL, allowMajorSkew);
    FUNCTION_LOG_END();

    ASSERT(backupStorage != NULL);
    ASSERT(backupPath != NULL);
    ASSERT(mysqldPath != NULL);

    MEM_CONTEXT_TEMP_BEGIN()
    {
        // 1. Read the backup manifest. NULL means the backup didn't include one — older mybackrest output. Refuse rather than
        //    guess: the operator should explicitly skip-check via a future flag if they want to drive recovery without metadata.
        MysqlBackupManifestParsed *const manifest = mysqlBackupManifestRead(backupStorage, backupPath);

        if (manifest == NULL)
        {
            THROW_FMT(
                FileMissingError,
                "%s/mybackrest_backup_info missing — cannot verify the recovery binary is compatible with this backup",
                strZ(backupPath));
        }

        LOG_INFO_FMT(
            "manifest: format=%u, vendor=%u, version=%u, taken=%s",
            manifest->format,
            (unsigned int)manifest->info->vendor,
            manifest->info->versionNum,
            manifest->backupTime != NULL ? strZ(manifest->backupTime) : "(unknown)");

        // 2. Probe the operator's mysqld binary
        MysqlBinaryInfo *const probe = mysqlBinaryProbe(mysqldPath);

        // 3. Run the vendor + version compatibility check
        String *const issue = mysqlBinaryCheckCompatibility(probe, manifest->info->vendor, manifest->info->versionNum);

        // 3b. Redo-format compatibility (separate check — a same-major-version match can still fail if the backup uses a
        //     redo format the older patch-level binary doesn't know about).
        String *const redoIssue = mysqlBinaryCheckRedoCompat(probe, manifest->info->redoFormatNum);

        if (redoIssue != NULL)
            THROW_FMT(OptionInvalidError, "redo-format compatibility FAILED: %s", strZ(redoIssue));

        // 3c. Engine-availability compatibility — refuse a backup whose engines the binary can't load.
        String *const engineIssue = mysqlBinaryCheckEngineCompat(
            probe, manifest->info->hasAria, manifest->info->hasIsam, manifest->info->hasTokudb, manifest->info->hasMyrocks);

        if (engineIssue != NULL)
            THROW_FMT(OptionInvalidError, "engine compatibility FAILED: %s", strZ(engineIssue));

        if (issue == NULL)
        {
            LOG_INFO_FMT(
                "compatibility check OK: backup vendor=%u version=%u redoFormat=%u ↔ binary vendor=%u version=%u",
                (unsigned int)manifest->info->vendor, manifest->info->versionNum, manifest->info->redoFormatNum,
                (unsigned int)probe->vendor, probe->versionNum);
        }
        else
        {
            // The check returns a non-NULL string for both hard incompatibility AND warnings (major-version skew). Distinguish
            // by inspecting the message — anything containing "INCOMPATIBLE" or "unsupported" is hard. Major-version skew is
            // tolerated when allowMajorSkew=true.
            if (strstr(strZ(issue), "unsupported") != NULL || strstr(strZ(issue), "mismatch:") != NULL)
            {
                if (allowMajorSkew && strstr(strZ(issue), "major-version mismatch") != NULL)
                {
                    LOG_WARN_FMT("compatibility check WARN (allowed by --allow-major-skew): %s", strZ(issue));
                }
                else
                {
                    THROW_FMT(OptionInvalidError, "compatibility check FAILED: %s", strZ(issue));
                }
            }
            else
            {
                LOG_WARN_FMT("compatibility check WARN: %s", strZ(issue));
            }
        }
    }
    MEM_CONTEXT_TEMP_END();

    FUNCTION_LOG_RETURN_VOID();
}
