/***********************************************************************************************************************************
Restore Prepare Phase

prepareWriteRecoveryFiles is implemented (pure file I/O); prepareInvokeMysqld remains a stub because spawning mysqld and verifying
graceful exit needs the existing common/exec.c lifecycle plumbing which Phase E will wire up properly.

The recovery cnf is a minimum-viable my.cnf that turns the restored datadir into a closed-door instance: skip-networking blocks
remote connections, --init-file=<sql> arranges for a SHUTDOWN; statement to fire as soon as recovery completes. The user can then
start mysqld normally with their own config.
***********************************************************************************************************************************/
#include <build.h>

#include "command/restore/prepare.h"
#include "common/debug.h"
#include "common/log.h"
#include "common/type/buffer.h"
#include "common/type/string.h"

#define MYBACKREST_RECOVERY_CNF                                     "mybackrest_recovery.cnf"
#define MYBACKREST_RECOVERY_SQL                                     "mybackrest_recovery.sql"
#define MYBACKREST_RECOVERY_PID                                     "mybackrest_recovery.pid"
#define MYBACKREST_RECOVERY_LOG                                     "mybackrest_recovery.log"

/**********************************************************************************************************************************/
FN_EXTERN void
prepareWriteRecoveryFiles(const Storage *const restoreStorage, const String *const restorePath, const String *const mysqldPath)
{
    FUNCTION_LOG_BEGIN(logLevelDebug);
        FUNCTION_LOG_PARAM(STORAGE, restoreStorage);
        FUNCTION_LOG_PARAM(STRING, restorePath);
        FUNCTION_LOG_PARAM(STRING, mysqldPath);
    FUNCTION_LOG_END();

    ASSERT(restoreStorage != NULL);
    ASSERT(restorePath != NULL);

    MEM_CONTEXT_TEMP_BEGIN()
    {
        // Compose the recovery cnf. Each option uses --long-form syntax so it works under either MySQL or MariaDB without
        // needing per-vendor branching.
        String *const cnf = strNewFmt(
            "# Generated by myBackRest — single-shot recovery configuration.\n"
            "# Run mysqld --defaults-file=%s/%s; the embedded init-file will issue SHUTDOWN; once InnoDB redo recovery\n"
            "# completes, leaving the datadir clean for normal startup with your own config afterwards.\n"
            "[mysqld]\n"
            "datadir = %s\n"
            "skip-networking = ON\n"
            "skip-grant-tables = OFF\n"
            "innodb-read-only = OFF\n"
            "innodb-fast-shutdown = 0\n"
            "init-file = %s/%s\n"
            "pid-file = %s/%s\n"
            "log-error = %s/%s\n",
            strZ(restorePath), MYBACKREST_RECOVERY_CNF,
            strZ(restorePath),
            strZ(restorePath), MYBACKREST_RECOVERY_SQL,
            strZ(restorePath), MYBACKREST_RECOVERY_PID,
            strZ(restorePath), MYBACKREST_RECOVERY_LOG);

        const String *const cnfPath = strNewFmt("%s/%s", strZ(restorePath), MYBACKREST_RECOVERY_CNF);
        storagePutP(storageNewWriteP(restoreStorage, cnfPath), BUFSTR(cnf));

        // Compose the SQL: a single SHUTDOWN; — innodb-fast-shutdown=0 ensures all dirty pages flush before the server exits, so
        // when the user's own mysqld starts later it sees a fully-clean datadir instead of replaying the recovery again.
        const String *const sql = STRDEF("-- Generated by myBackRest. Fires once via --init-file at end of recovery.\nSHUTDOWN;\n");
        const String *const sqlPath = strNewFmt("%s/%s", strZ(restorePath), MYBACKREST_RECOVERY_SQL);
        storagePutP(storageNewWriteP(restoreStorage, sqlPath), BUFSTR(sql));

        // Belt-and-braces: log the mysqld path even though we don't invoke it here. prepareInvokeMysqld is responsible for that.
        if (mysqldPath != NULL)
            LOG_INFO_FMT("recovery files written; run: %s --defaults-file=%s/%s", strZ(mysqldPath), strZ(restorePath), MYBACKREST_RECOVERY_CNF);
        else
            LOG_INFO_FMT("recovery files written: %s and %s", strZ(cnfPath), strZ(sqlPath));
    }
    MEM_CONTEXT_TEMP_END();

    FUNCTION_LOG_RETURN_VOID();
}

/**********************************************************************************************************************************/
FN_EXTERN void
prepareInvokeMysqld(const String *const mysqldPath, const String *const restorePath)
{
    FUNCTION_LOG_BEGIN(logLevelDebug);
        FUNCTION_LOG_PARAM(STRING, mysqldPath);
        FUNCTION_LOG_PARAM(STRING, restorePath);
    FUNCTION_LOG_END();

    ASSERT(mysqldPath != NULL);
    ASSERT(restorePath != NULL);

    // TODO(myBackRest-E): use common/exec.c to fork+exec; capture stdout/stderr to recovery.log; check exit code; remove pid file.
    // Reference for the lifecycle pattern: src/command/control/start.c which already invokes external processes.
    THROW(AssertError, "TODO(myBackRest-E): prepareInvokeMysqld — fork+exec mysqld + wait for SHUTDOWN exit");
}
