/***********************************************************************************************************************************
Restore Prepare Phase

Both prepareWriteRecoveryFiles and prepareInvokeMysqld are now real. Together they implement the user-chosen mysqld-driven crash
recovery hand-off — myBackRest writes a single-shot recovery cnf + sql, then forks mysqld which replays InnoDB redo and exits via
SHUTDOWN. No GPLv2 InnoDB recovery code is linked into the MIT mybackrest binary.
***********************************************************************************************************************************/
#include <build.h>

#include <stdlib.h>
#include <sys/wait.h>
#include <unistd.h>

#include "command/restore/prepare.h"
#include "common/debug.h"
#include "common/fork.h"
#include "common/log.h"
#include "common/type/buffer.h"
#include "common/type/string.h"
#include "common/type/stringList.h"

#define MYBACKREST_RECOVERY_CNF                                     "mybackrest_recovery.cnf"
#define MYBACKREST_RECOVERY_SQL                                     "mybackrest_recovery.sql"
#define MYBACKREST_RECOVERY_PID                                     "mybackrest_recovery.pid"
#define MYBACKREST_RECOVERY_LOG                                     "mybackrest_recovery.log"

/**********************************************************************************************************************************/
FN_EXTERN void
prepareWriteRecoveryFiles(const Storage *const restoreStorage, const String *const restorePath, const String *const mysqldPath)
{
    FUNCTION_LOG_BEGIN(logLevelDebug);
        FUNCTION_LOG_PARAM(STORAGE, restoreStorage);
        FUNCTION_LOG_PARAM(STRING, restorePath);
        FUNCTION_LOG_PARAM(STRING, mysqldPath);
    FUNCTION_LOG_END();

    ASSERT(restoreStorage != NULL);
    ASSERT(restorePath != NULL);

    MEM_CONTEXT_TEMP_BEGIN()
    {
        // Compose the recovery cnf. Each option uses --long-form syntax so it works under either MySQL or MariaDB without
        // needing per-vendor branching.
        String *const cnf = strNewFmt(
            "# Generated by myBackRest — single-shot recovery configuration.\n"
            "# Run mysqld --defaults-file=%s/%s; the embedded init-file will issue SHUTDOWN; once InnoDB redo recovery\n"
            "# completes, leaving the datadir clean for normal startup with your own config afterwards.\n"
            "[mysqld]\n"
            "datadir = %s\n"
            "skip-networking = ON\n"
            "skip-grant-tables = OFF\n"
            "innodb-read-only = OFF\n"
            "innodb-fast-shutdown = 0\n"
            "init-file = %s/%s\n"
            "pid-file = %s/%s\n"
            "log-error = %s/%s\n",
            strZ(restorePath), MYBACKREST_RECOVERY_CNF,
            strZ(restorePath),
            strZ(restorePath), MYBACKREST_RECOVERY_SQL,
            strZ(restorePath), MYBACKREST_RECOVERY_PID,
            strZ(restorePath), MYBACKREST_RECOVERY_LOG);

        const String *const cnfPath = strNewFmt("%s/%s", strZ(restorePath), MYBACKREST_RECOVERY_CNF);
        storagePutP(storageNewWriteP(restoreStorage, cnfPath), BUFSTR(cnf));

        // Compose the SQL: a single SHUTDOWN; — innodb-fast-shutdown=0 ensures all dirty pages flush before the server exits, so
        // when the user's own mysqld starts later it sees a fully-clean datadir instead of replaying the recovery again.
        const String *const sql = STRDEF("-- Generated by myBackRest. Fires once via --init-file at end of recovery.\nSHUTDOWN;\n");
        const String *const sqlPath = strNewFmt("%s/%s", strZ(restorePath), MYBACKREST_RECOVERY_SQL);
        storagePutP(storageNewWriteP(restoreStorage, sqlPath), BUFSTR(sql));

        if (mysqldPath != NULL)
            LOG_INFO_FMT("recovery files written; run: %s --defaults-file=%s/%s", strZ(mysqldPath), strZ(restorePath), MYBACKREST_RECOVERY_CNF);
        else
            LOG_INFO_FMT("recovery files written: %s and %s", strZ(cnfPath), strZ(sqlPath));
    }
    MEM_CONTEXT_TEMP_END();

    FUNCTION_LOG_RETURN_VOID();
}

/**********************************************************************************************************************************/
FN_EXTERN void
prepareInvokeMysqld(const String *const mysqldPath, const String *const restorePath)
{
    FUNCTION_LOG_BEGIN(logLevelDebug);
        FUNCTION_LOG_PARAM(STRING, mysqldPath);
        FUNCTION_LOG_PARAM(STRING, restorePath);
    FUNCTION_LOG_END();

    ASSERT(mysqldPath != NULL);
    ASSERT(restorePath != NULL);

    MEM_CONTEXT_TEMP_BEGIN()
    {
        // Build argv: [mysqld, --defaults-file=<restorePath>/mybackrest_recovery.cnf]. Use the long-form so the path is
        // unambiguous; mysqld parses it the same on MySQL and MariaDB.
        StringList *const argv = strLstNew();
        strLstAdd(argv, mysqldPath);
        strLstAdd(argv, strNewFmt("--defaults-file=%s/%s", strZ(restorePath), MYBACKREST_RECOVERY_CNF));

        LOG_INFO_FMT(
            "invoking mysqld for one-shot recovery: %s --defaults-file=%s/%s",
            strZ(mysqldPath), strZ(restorePath), MYBACKREST_RECOVERY_CNF);

        const pid_t pid = forkSafe();

        if (pid == 0)
        {
            // Child — exec mysqld. The recovery cnf points log-error at <restorePath>/mybackrest_recovery.log so we don't need
            // to pipe stdout/stderr; the operator can `tail` that file if recovery fails.
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wcast-qual"
            THROW_ON_SYS_ERROR_FMT(
                execvp(strZ(strLstGet(argv, 0)), UNCONSTIFY(char **, strLstPtr(argv))) == -1, ExecuteError,
                "unable to exec mysqld at '%s'", strZ(mysqldPath));
#pragma GCC diagnostic pop

            exit(127);                                                  // Unreachable, but keeps the compiler happy
        }

        // Parent — wait for the child to exit. mysqld will recover, run the init-file (SHUTDOWN;), and exit cleanly. Recovery
        // can take a long time on large redo logs so no timeout — the operator can SIGTERM the parent if needed.
        int status;
        const pid_t waited = waitpid(pid, &status, 0);

        THROW_ON_SYS_ERROR(waited == -1, ExecuteError, "waitpid failed for mysqld recovery");

        if (!WIFEXITED(status))
        {
            THROW_FMT(
                ExecuteError, "mysqld recovery process did not exit normally — check %s/%s for details",
                strZ(restorePath), MYBACKREST_RECOVERY_LOG);
        }

        const int exitCode = WEXITSTATUS(status);

        if (exitCode != 0)
        {
            THROW_FMT(
                ExecuteError, "mysqld recovery exited with status %d — check %s/%s for details",
                exitCode, strZ(restorePath), MYBACKREST_RECOVERY_LOG);
        }

        LOG_INFO("mysqld recovery completed; datadir is clean and ready for normal startup");
    }
    MEM_CONTEXT_TEMP_END();

    FUNCTION_LOG_RETURN_VOID();
}
